name: testes-e-validacao

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Configurar o Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependências
      run: npm install --legacy-peer-deps

    - name: Rodar o ESLint
      run: npx eslint .